tried reworking the action again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,10 +14,18 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
+      - name: Verify Icon File
+        run: |
+          if [ ! -f autodako/edvin.ico ]; then
+            echo "Icon file not found!"
+            exit 1
+          fi
+
       - name: Ahk2Exe
         uses: CCCC-L/Action-Ahk2Exe@main
         with:
           in: autodako/autodako.ahk
+        working-directory: autodako
 
       - name: Create Release
         id: create_release
@@ -28,7 +36,6 @@ jobs:
           tag_name: ${{ steps.generate_tag.outputs.tag }}
           release_name: Release ${{ steps.generate_tag.outputs.tag }}
           prerelease: false
-
 
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
